Repository jhradilek/asciidoctor-dita-vale, pull requests merged in 2025-07, with the labels that each got.

#85 Issue #84: Do not report nested description lists
  fixtures/TaskStep/ignore_description_lists.adoc
  styles/AsciiDocDITA/TaskStep.yml
  test/TaskStep.bats
Labels: enhancement

#86 Report content after unsupported block titles
  fixtures/TaskStep/ignore_block_titles.adoc
  fixtures/TaskStep/report_block_titles.adoc
  styles/AsciiDocDITA/TaskStep.yml
  test/TaskStep.bats
Labels: bug

#90 Issue #89: Recognize content type separated by more than one space
  styles/AsciiDocDITA/BlockTitle.yml
  styles/AsciiDocDITA/TaskDuplicate.yml
  styles/AsciiDocDITA/TaskExample.yml
  styles/AsciiDocDITA/TaskSection.yml
  styles/AsciiDocDITA/TaskStep.yml
  styles/AsciiDocDITA/TaskTitle.yml
Labels: bug

#91 Correct the regular expression for attribute references
  fixtures/AttributeReference/report_custom_attributes.adoc
  fixtures/LinkAttribute/report_attribute_references.adoc
  styles/AsciiDocDITA/AttributeReference.yml
  styles/AsciiDocDITA/LinkAttribute.yml
  test/AttributeReference.bats
Labels: bug

#92 Udate the LinkAttribute and AttributeReference rules to ignore Bash variables
  fixtures/AttributeReference/ignore_bash_variables.adoc
  fixtures/LinkAttribute/ignore_bash_variables.adoc
  styles/AsciiDocDITA/AttributeReference.yml
  styles/AsciiDocDITA/LinkAttribute.yml
  test/AttributeReference.bats
  test/LinkAttribute.bats
Labels: enhancement

#95 Ignore links wiht attributes in line comments
  fixtures/LinkAttribute/ignore_comments.adoc
  styles/AsciiDocDITA/LinkAttribute.yml
  test/LinkAttribute.bats
Labels: enhancement

#99 Removed the $ sign from the commands so they are easier to use
  README.md
Labels: documentation
